# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    build: 
      context: ./db
      target: postgres
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mySecretPassword
      POSTGRES_DB: qr_code
    ports:
      - 5432:5432

# PARA CONECTAR NO ADMINER AO INVES DE USAR LOCALHOST TEM QUE USAR db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
    pgdata: